"""added a quantity section to the cart product

Revision ID: d8704109f8f1
Revises: 892184886be0
Create Date: 2024-04-11 20:58:37.235556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8704109f8f1'
down_revision = '892184886be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('orderproducts', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderproducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
